/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const createElement: typeof import('@/utils/dom.ts')['createElement']
  const createElementsFragment: typeof import('@/utils/dom.ts')['createElementsFragment']
}
