export const initialList = [
  {
    id: 0,
    category: '한식',
    name: '가_한식',
    distance: '30',
    description: '가_한식입니다.',
    link: 'http://www.naver.com',
    isFavorite: false,
  },
  {
    id: 1,
    category: '한식',
    name: '나_한식',
    distance: '15',
    description: '나_한식입니다.',
    link: 'http://www.naver.com',
    isFavorite: false,
  },
  {
    id: 2,
    category: '중식',
    name: '다_중식',
    distance: '10',
    description: '다_중식입니다.',
    link: 'http://www.naver.com',
    isFavorite: false,
  },
  {
    id: 3,
    category: '일식',
    name: '라_일식',
    distance: '5',
    description: '라_일식입니다',
    link: '',
    isFavorite: false,
  },
  {
    id: 4,
    category: '양식',
    name: '하_오분거리 양식',
    distance: '5',
    description: '5분거리',
    link: '',
    isFavorite: false,
  },
  {
    id: 5,
    category: '아시안',
    name: '하_오분거리 아시안',
    distance: '5',
    description: '5분거리',
    link: '',
    isFavorite: false,
  },
];
