export const CATEGORY_TEST_CASE = [
  {
    id: 0,
    category: '한식',
    name: '가_한식',
    distance: '30',
    description: '가_한식입니다.',
    link: 'http://www.naver.com',
    isFavorite: false,
  },
  {
    id: 1,
    category: '한식',
    name: '나_한식',
    distance: '15',
    description: '나_한식입니다.',
    link: 'http://www.naver.com',
    isFavorite: false,
  },
  {
    id: 2,
    category: '중식',
    name: '다_중식',
    distance: '10',
    description: '다_중식입니다.',
    link: 'http://www.naver.com',
    isFavorite: false,
  },
  {
    id: 3,
    category: '일식',
    name: '라_일식',
    distance: '5',
    description: '라_일식입니다',
    link: '',
    isFavorite: false,
  },
  {
    id: 4,
    category: '양식',
    name: '하_오분거리 양식',
    distance: '5',
    description: '5분거리',
    link: '',
    isFavorite: false,
  },
  {
    id: 5,
    category: '아시안',
    name: '하_오분거리 아시안',
    distance: '5',
    description: '5분거리',
    link: '',
    isFavorite: false,
  },
];

export const SORTING_TEST_CASE = [
  {
    id: 0,
    category: '한식',
    name: '다섯번째 거리',
    distance: '30',
    description: '한식입니다.',
    link: 'http://www.naver.com',
    isFavorite: false,
  },
  {
    id: 1,
    category: '한식',
    name: '세번째 거리',
    distance: '15',
    description: '한식입니다.',
    link: 'http://www.naver.com',
    isFavorite: false,
  },
  {
    id: 2,
    category: '한식',
    name: '두번째 거리',
    distance: '10',
    description: '한식입니다.',
    link: 'http://www.naver.com',
    isFavorite: false,
  },
  {
    id: 3,
    category: '한식',
    name: '네번째 거리',
    distance: '20',
    description: '한식입니다.',
    link: 'http://www.naver.com',
    isFavorite: false,
  },
  {
    id: 4,
    category: '한식',
    name: '첫번째 거리',
    distance: '5',
    description: '한식입니다.',
    link: 'http://www.naver.com',
    isFavorite: false,
  },
];

export const FAVORITES_TEST_CASE = [
  {
    id: 0,
    category: '한식',
    name: '매우_좋아요',
    distance: '5',
    description: 'good',
    link: 'http://www.naver.com',
    isFavorite: false,
  },
  {
    id: 1,
    category: '한식',
    name: '안좋아요',
    distance: '5',
    description: 'good',
    link: 'http://www.naver.com',
    isFavorite: false,
  },
  {
    id: 2,
    category: '한식',
    name: '안좋아요',
    distance: '5',
    description: 'good',
    link: 'http://www.naver.com',
    isFavorite: false,
  },
  {
    id: 3,
    category: '한식',
    name: '안좋아요',
    distance: '5',
    description: 'good',
    link: 'http://www.naver.com',
    isFavorite: false,
  },
];

export const RESTAURANT_INPUT_CASE = {
  category: '한식',
  name: '얌샘김밥',
  distance: '5',
  description: 'good',
  link: 'http://www.naver.com',
};
