import AddRestaurantForm from './AddRestaurantForm';
import AddRestaurantModal from './AddRestuarntModal';
import AddSelect from './AddSelect';
import Button from './Button';
import CategoryImage from './CategoryImage';
import FavoriteImage from './FavoriteImage';
import FilterBox from './FilterBox';
import Header from './Header';
import Modal from './Modal';
import RestaurantBox from './RestaurantBox';
import RestaurantBoxes from './RestaurantBoxes';
import RestaurantDetail from './RestaurantDetail';
import RestaurantDetailModal from './RestaurantDetailModal';
import RestaurantTab from './RestaurantTab';
import NameInput from './NameInput';
import DescriptionInput from './DescriptionInput';
import LinkInput from './LinkInput';

customElements.define('add-select', AddSelect);
customElements.define('name-input', NameInput);
customElements.define('description-input', DescriptionInput);
customElements.define('link-input', LinkInput);
customElements.define('add-restaurant-form', AddRestaurantForm);
customElements.define('add-restaurant-modal', AddRestaurantModal);
customElements.define('lunch-button', Button);
customElements.define('category-image', CategoryImage);
customElements.define('favorite-image', FavoriteImage);
customElements.define('filter-box', FilterBox);
customElements.define('lunch-header', Header);
customElements.define('lunch-modal', Modal);
customElements.define('restaurant-box', RestaurantBox);
customElements.define('restaurant-boxes', RestaurantBoxes);
customElements.define('restaurant-detail', RestaurantDetail);
customElements.define('restaurant-detail-modal', RestaurantDetailModal);
customElements.define('restaurant-tab', RestaurantTab);
