const RESTAURANT_ADD_FORM_INPUT_RULES = {
  MAX_NAME_LENGTH: 20,
  MIN_NAME_LENGTH: 1,
  MAX_DESC_LENGTH: 300,
  LINK_REGEX: /^(https?:\/\/)?www\.[a-zA-Z0-9-]+\.[a-zA-Z]{2,}$/,
};

export default RESTAURANT_ADD_FORM_INPUT_RULES;
