const RESTAURANT_LIST_ITEM_IS_FAVORITED_CONTAINER_COMPONENT_DATA = Object.freeze({
  TAG_CLASS_NAME: 'favorited-icon-container',
});

export default RESTAURANT_LIST_ITEM_IS_FAVORITED_CONTAINER_COMPONENT_DATA;
