export { default as addButton } from "../../templates/add-button.png";
export { default as categoryKorean } from "../../templates/category-korean.png";
export { default as categoryAsian } from "../../templates/category-asian.png";
export { default as categoryJapanese } from "../../templates/category-japanese.png";
export { default as categoryChinese } from "../../templates/category-chinese.png";
export { default as categoryWestern } from "../../templates/category-western.png";
export { default as categoryEtc } from "../../templates/category-etc.png";
export { default as linedFavoriteIcon } from "../../templates/favorite-icon-lined.png";
export { default as filledFavoriteIcon } from "../../templates/favorite-icon-filled.png";
