import "../style.css";
import "./App.ts";
import "../assets/add-button.png";
import "../assets/category-korean.png";
import "../assets/category-japanese.png";
import "../assets/category-chinese.png";
import "../assets/category-asian.png";
import "../assets/category-western.png";
import "../assets/category-etc.png";
