import "../templates/style.css";
import "./components/Header.js";
import "./components/OptionSelector.js";
import "./components/RestaurantList.js";
import "./components/RestaurantItem.js";
import "./components/RestaurantAddForm/RestaurantNameInput.js";
import "./components/RestaurantAddForm/RestaurantOption.js";
import "./components/RestaurantAddForm/index.js";
import "./components/MenuApp.js";
